# Generated by Django 3.0.4 on 2020-03-12 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Attainia_Api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppUser',
            new_name='User',
        ),
    ]
